---
title: "Data Manipulation"
output: github_document
---

This document will show how to manipulate data.

Import the two datasets that we're going to manipulate.

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv('data/FAS_litters.csv', na = c("NA","",".")) #in this format, gd0 and gd18 are dbl (numerical)
litters_df = janitor::clean_names(litters_df)
litters_df

pups_df = read_csv('data/FAS_pups.csv', na = c("NA", "", "."))
pups_df = janitor::clean_names(pups_df)
pups_df
```

```{r}
#litters_df = read_csv("./data/FAS_litters.csv") #in this format, the GD0 and GD18 are character
#litters_df
```

## `select`

Use `select()` to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group:gd18_weight)
```

```{r}
select(litters_df, -pups_survive) #delete the column pups_survive
```

```{r}
select(litters_df, -(group:gd18_weight)) 
```

Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)

rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))

select(litters_df, contains("pups"))
```

```{r}
select(litters_df, litter_number, gd0_weight, everything()) #move litter_number and gd0 to beginning

relocate(litters_df, litter_number, gd0_weight) #relocate to the beginning
```

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`

```{r}
filter(litters_df, gd_of_birth == 20) 

filter(litters_df, gd_of_birth == 19)
```

```{r}
filter(litters_df, pups_born_alive > 8)
filter(litters_df, pups_born_alive >= 8)
```

```{r}
filter(litters_df, pups_born_alive != 9) #not equal to 9
```

```{r}
filter(litters_df, group == "Low8")
filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive == 8)

filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(pups_df, sex == 1)
filter(pups_df, pd_walk < 11, sex == 2)
```

Drop missing data

```{r}
drop_na(litters_df) #drop any missing data 

drop_na(litters_df, gd0_weight) #drop missing data in gd0_weight
```

## `mutate`

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight) #create new variable - wt_gain

mutate(litters_df, sq_pups = pups_born_alive^2)

mutate(litters_df, group = str_to_lower(group)) #in lower case

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```









